apiVersion: v1
kind: Service
metadata:
  name: amd-frontend-service
  labels:
    app: amd-frontend
spec:
  type: LoadBalancer
  selector:
    app: amd-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
